### ISSUE TITLE
Game crashes after entering map "Court of 1000 Warriors"

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [whirledtsar/Hexen-2---Shadows-of-Chaos-fork#96]
After completing the Trial of Fire (if that's the correct name, I don't remember), after crossing the portal to the "Court of 1000 Warriors", the game crashes. The terminal output is:

```
Court of 1000 Warriors
Loading game from /home/williamberrutti/.hexen2/soc/meso2.gip...
Host_Error: CL_ParseServerMessage: svc_updatename > MAX_CLIENTS
Client Cyantusk removed
```

System Details:

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.10.84-1-MANJARO (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa DRI Intel® HD Graphics

Engine Used:

Hammer of Thrion (from AUR: https://aur.archlinux.org/packages/hexen2)
Version: 1.5.9-1

**Comment by whirledtsar** [comment]
Hi, I recommend using the uHexen2 fork of Hammer Of Thyrion, because it's more up to date and is what I test the mod with. I just tried opening the Hall Of 1000 Warriors map and going back and forth between other levels, and it doesnt crash.

You can download the latest testing version (the latest "stable" version is very outdated) from here: https://hexenworld.org/

**Comment by WilliamWeberBerrutti** [comment]
Oh ok, I'll test it as soon as I can and report back! Unfortunately, it seems uHexen2 isn't avaliable as a package, so I have to manually download it.

**Comment by WilliamWeberBerrutti** [comment]
It seems the problem is gone! I'm not used to HeXen 2 source ports! Thank you for the suggestion!
